WOKER_COST_PER_DAY = 300
WOKER_COST_PER_HOUR = WOKER_COST_PER_DAY / 8


AERIAL_MATERIAL_COST_PER_METER = 500
SEMI_AERIAL_MATERIAL_COST_PER_METER = 750
DUCT_COST_MATERIAL_PER_METER = 900


AERIAL_DURATION_PER_METER = 2
SEMI_AERIAL_DURATION_PER_METER = 4
DUCT_DURATION_PER_METER = 5


MAX_WORKERS_PER_INFRA = 4


AERIAL_COST_PER_METER = AERIAL_MATERIAL_COST_PER_METER + AERIAL_DURATION_PER_METER * WOKER_COST_PER_HOUR
SEMI_AERIAL_COST_PER_METER = SEMI_AERIAL_MATERIAL_COST_PER_METER + SEMI_AERIAL_DURATION_PER_METER * WOKER_COST_PER_HOUR
DUCT_COST_PER_METER = DUCT_COST_MATERIAL_PER_METER + DUCT_DURATION_PER_METER * WOKER_COST_PER_HOUR